name: ci

on:
    push:
        tags:
            - 'v*.*.*'

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - uses: actions/setup-node@v2
              with:
               node-version: '14'

            - name: Install Dependency
              run: |
               npm install

            - name: Bundle package
              run: |
               npm run archive

            - name: Create Release
              uses: softprops/action-gh-release@v1
              with:
                  files: |
                    dist/chrome/aws-extend-switch-roles.zip
